Wilmer -> feat: Add repository and extension method
ManasesLovera/bookStore pull request #24
Opened 2024-09-10 03:24 UTC by Wil-JsDev

### Repository

Add three repositories and the generic repository will have the methods to handle the database logic.

### Extension Method
This method works to handle dependency injections better.

2024-09-10 03:51 UTC, ManasesLovera commented on services/OrderService/Repository/OrderItemRepository.cs
> +        return order == null ? true : false;
it should be return order == null ? false : true; or order != null ? true : false. This is returning true if it's null which is the opposite it should do.

2024-09-10 03:53 UTC, ManasesLovera commented on services/OrderService/Extensions/ServiceExtension.cs
> +public static class ServiceExtensio
ServiceExtensions* with the 's'

2024-09-10 03:54 UTC, ManasesLovera commented on services/OrderService/Repository/OrderRepository.cs
> +        return order == null ? true : false;
Looks like the same error as the previous one, please correct this is sending true when it doesn't exist and sending false when it does exist.

2024-09-10 03:56 UTC, ManasesLovera requested changes
I like the IGenericRepository, but please fix the issues I marked, after that please push the new commits and leave a comment that once you fixes this issue.

2024-09-10 12:33 UTC, Wil-JsDev commented
Done!

2024-09-11 01:44 UTC, ManasesLovera approved these changes
Everything looks great now, good job!

2024-09-11 01:44 UTC, merged